name: "general"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test_fmt_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Maximize build space
        uses: AdityaGarg8/remove-unwanted-software@v2
        with:
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'

      - name: Install nix
        uses: cachix/install-nix-action@v27
        with:
          install_url: https://releases.nixos.org/nix/nix-2.24.4/install

      - uses: cachix/cachix-action@v15
        with:
          name: holochain-ci

      - name: rustfmt check
        run: |
          cd $GITHUB_WORKSPACE
          nix develop --command cargo fmt --all --check

      - name: clippy check
        run: |
          cd $GITHUB_WORKSPACE
          nix develop --command cargo clippy --all-features --all-targets -- -D warnings

      - name: integration_tests
        run: |
          cd $GITHUB_WORKSPACE
          nix develop --command cargo test --no-fail-fast
